.TH ABRAFLEXI-ZABBIX-NETWORK 1 "March 2026" "abraflexi-zabbix" "User Commands"
.SH NAME
abraflexi-zabbix-network \- Zabbix check for AbraFlexi network connectivity
.SH SYNOPSIS
.B abraflexi-zabbix-network
.SH DESCRIPTION
.B abraflexi-zabbix-network
is a script that evaluates the network connectivity to the AbraFlexi server for monitoring purposes in Zabbix.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
