.TH ABRAFLEXI-ZABBIX-STATUS 1 "March 2026" "abraflexi-zabbix" "User Commands"
.SH NAME
abraflexi-zabbix-status \- Zabbix check for AbraFlexi status
.SH SYNOPSIS
.B abraflexi-zabbix-status
.SH DESCRIPTION
.B abraflexi-zabbix-status
is a script that evaluates the system status of the AbraFlexi server for monitoring purposes in Zabbix.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
