.TH ABRAFLEXI-ZABBIX-LLD-COMPANY 1 "March 2026" "abraflexi-zabbix" "User Commands"
.SH NAME
abraflexi-zabbix-lld-company \- Zabbix LLD script for AbraFlexi companies
.SH SYNOPSIS
.B abraflexi-zabbix-lld-company
.SH DESCRIPTION
.B abraflexi-zabbix-lld-company
is a script that outputs a JSON array formatted for Zabbix Low Level Discovery (LLD), listing the active companies configured on the AbraFlexi server.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
